# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='plan',
            new_name='description',
        ),
    ]
